# Generated by Django 2.1.3 on 2018-11-11 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollsModel',
            fields=[
                ('vote_id', models.CharField(db_column='VOTE_ID', max_length=200, primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, db_column='USER', max_length=200, null=True)),
                ('email', models.CharField(blank=True, db_column='EMAIL', max_length=200, null=True)),
                ('vote_choice', models.IntegerField(default=0)),
                ('vote_date', models.DateTimeField(db_column='VOTE_DATE')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue.IssueModel')),
            ],
            options={
                'db_table': 'POLLS',
            },
        ),
    ]
